@startuml
class Libro {
   -isbn:String;
   -titulo:String;
   -autor:String;
   -paginas:int;
   +Libro()
   +getIsbn():String
   +getTitulo():String
   +setIsbn(String)
   +setTitulo(String)
   +setAutor(String)
   +setPaginas(int)
   +{static}generarIsbn(int):String
   +{static}generarIsbnV2(int): String
   +{static}generarIsbnV3(int): String
   +{static}generarIsbnV4():String
   +{static}generarIsbnV5():String
   -{static}getInt(int, int):int
   - esIsbmValido(String): boolean
}
@enduml

